---
- include: compat.yml

- include: include_vars.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Check if android studio is installed
  command: grep {{android_sdk_build}} /opt/android-sdk-{{package_ext}}
  register: install
  failed_when: False
  changed_when: False

- name: Download Android SDK .zip
  command: >
    wget -q -O {{local_package_dir}}/android_sdk_download.{{package_ext}}
    {{dl_base_url}}{{version}}{{package_os}}.{{package_ext}}
  args:
    creates: "{{local_package_dir}}/android_sdk_download.{{package_ext}}"
  when: install|failed

- name: install unzip with default package manager
  action: "{{backcompat_pkg_mgr}} name={{package_name}}"
  sudo: yes
  when: (backcompat_pkg_mgr == "yum" or backcompat_pkg_mgr == "apt") and package_ext == "zip"

# Use command since dnf was only added as a module in ansible 1.9.0
- name: install unzip with dnf
  command: dnf install -y {{package_name}}
  args:
    creates: /usr/bin/unzip
  sudo: yes
  when: backcompat_pkg_mgr == "dnf" and package_ext == "zip"

- name: Unzip Android Studio
  command: unzip -od /opt "{{local_package_dir}}/android_sdk_download.{{package_ext}}"
  sudo: True
  when: install|failed and package_ext == "zip"

- name: Untar Android Studio
  command: tar xvfoz "{{local_package_dir}}/android_sdk_download.{{package_ext}}"
  sudo: True
  when: install|failed and package_ext == "tgz"
  args:
    chdir: /opt
    creates: /opt/android-sdk{{package_os}}
